name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: make install
      
    - name: run login tests
      run: make run-login
    - name: run users tests
      run: make run-users
    - name: run products tests
      run: make run-products
    - name: run carts tests
      run: make run-carts
