name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      uses: Jianbo-Zhu/jianbo-robot-action@v0.0.3
      with:
        railflow_key: ${{ secrets.RAILFLOW_KEY }}
        testrail_username: ${{ secrets.TESTRAIL_USERNAME }}
        testrail_password: ${{ secrets.TESTRAIL_PASSWORD }}
        testrail_url: https://tr.railflow.io/
        testrail_project: robot-action-x-single
        testrail_test_plan: tp
        robot_tests_dir: .
        
